/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as IntranetLoginRouteImport } from './routes/intranet/login'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as IntranetAuthedRouteRouteImport } from './routes/intranet/_authed/route'
import { Route as IntranetAuthedIndexRouteImport } from './routes/intranet/_authed/index'
import { Route as IntranetAuthedReunioesRouteImport } from './routes/intranet/_authed/reunioes'
import { Route as IntranetAuthedRelatoriosRouteImport } from './routes/intranet/_authed/relatorios'
import { Route as IntranetAuthedProjetosRouteImport } from './routes/intranet/_authed/projetos'
import { Route as IntranetAuthedFinanceiroRouteImport } from './routes/intranet/_authed/financeiro'
import { Route as IntranetAuthedDocumentosRouteImport } from './routes/intranet/_authed/documentos'
import { Route as IntranetAuthedClientesRouteImport } from './routes/intranet/_authed/clientes'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const IntranetLoginRoute = IntranetLoginRouteImport.update({
  id: '/intranet/login',
  path: '/intranet/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const IntranetAuthedRouteRoute = IntranetAuthedRouteRouteImport.update({
  id: '/intranet/_authed',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any)
const IntranetAuthedIndexRoute = IntranetAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntranetAuthedRouteRoute,
} as any)
const IntranetAuthedReunioesRoute = IntranetAuthedReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => IntranetAuthedRouteRoute,
} as any)
const IntranetAuthedRelatoriosRoute =
  IntranetAuthedRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => IntranetAuthedRouteRoute,
  } as any)
const IntranetAuthedProjetosRoute = IntranetAuthedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => IntranetAuthedRouteRoute,
} as any)
const IntranetAuthedFinanceiroRoute =
  IntranetAuthedFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => IntranetAuthedRouteRoute,
  } as any)
const IntranetAuthedDocumentosRoute =
  IntranetAuthedDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => IntranetAuthedRouteRoute,
  } as any)
const IntranetAuthedClientesRoute = IntranetAuthedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => IntranetAuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/intranet': typeof IntranetAuthedRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/intranet/login': typeof IntranetLoginRoute
  '/blog/': typeof BlogIndexRoute
  '/intranet/clientes': typeof IntranetAuthedClientesRoute
  '/intranet/documentos': typeof IntranetAuthedDocumentosRoute
  '/intranet/financeiro': typeof IntranetAuthedFinanceiroRoute
  '/intranet/projetos': typeof IntranetAuthedProjetosRoute
  '/intranet/relatorios': typeof IntranetAuthedRelatoriosRoute
  '/intranet/reunioes': typeof IntranetAuthedReunioesRoute
  '/intranet/': typeof IntranetAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/intranet/login': typeof IntranetLoginRoute
  '/blog': typeof BlogIndexRoute
  '/intranet/clientes': typeof IntranetAuthedClientesRoute
  '/intranet/documentos': typeof IntranetAuthedDocumentosRoute
  '/intranet/financeiro': typeof IntranetAuthedFinanceiroRoute
  '/intranet/projetos': typeof IntranetAuthedProjetosRoute
  '/intranet/relatorios': typeof IntranetAuthedRelatoriosRoute
  '/intranet/reunioes': typeof IntranetAuthedReunioesRoute
  '/intranet': typeof IntranetAuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/intranet/_authed': typeof IntranetAuthedRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/intranet/login': typeof IntranetLoginRoute
  '/blog/': typeof BlogIndexRoute
  '/intranet/_authed/clientes': typeof IntranetAuthedClientesRoute
  '/intranet/_authed/documentos': typeof IntranetAuthedDocumentosRoute
  '/intranet/_authed/financeiro': typeof IntranetAuthedFinanceiroRoute
  '/intranet/_authed/projetos': typeof IntranetAuthedProjetosRoute
  '/intranet/_authed/relatorios': typeof IntranetAuthedRelatoriosRoute
  '/intranet/_authed/reunioes': typeof IntranetAuthedReunioesRoute
  '/intranet/_authed/': typeof IntranetAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cases'
    | '/contato'
    | '/privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/intranet'
    | '/blog/$slug'
    | '/intranet/login'
    | '/blog/'
    | '/intranet/clientes'
    | '/intranet/documentos'
    | '/intranet/financeiro'
    | '/intranet/projetos'
    | '/intranet/relatorios'
    | '/intranet/reunioes'
    | '/intranet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/contato'
    | '/privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
    | '/intranet/login'
    | '/blog'
    | '/intranet/clientes'
    | '/intranet/documentos'
    | '/intranet/financeiro'
    | '/intranet/projetos'
    | '/intranet/relatorios'
    | '/intranet/reunioes'
    | '/intranet'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cases'
    | '/contato'
    | '/privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/intranet/_authed'
    | '/blog/$slug'
    | '/intranet/login'
    | '/blog/'
    | '/intranet/_authed/clientes'
    | '/intranet/_authed/documentos'
    | '/intranet/_authed/financeiro'
    | '/intranet/_authed/projetos'
    | '/intranet/_authed/relatorios'
    | '/intranet/_authed/reunioes'
    | '/intranet/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CasesRoute: typeof CasesRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  IntranetAuthedRouteRoute: typeof IntranetAuthedRouteRouteWithChildren
  IntranetLoginRoute: typeof IntranetLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/intranet/login': {
      id: '/intranet/login'
      path: '/intranet/login'
      fullPath: '/intranet/login'
      preLoaderRoute: typeof IntranetLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/intranet/_authed': {
      id: '/intranet/_authed'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetAuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet/_authed/': {
      id: '/intranet/_authed/'
      path: '/'
      fullPath: '/intranet/'
      preLoaderRoute: typeof IntranetAuthedIndexRouteImport
      parentRoute: typeof IntranetAuthedRouteRoute
    }
    '/intranet/_authed/reunioes': {
      id: '/intranet/_authed/reunioes'
      path: '/reunioes'
      fullPath: '/intranet/reunioes'
      preLoaderRoute: typeof IntranetAuthedReunioesRouteImport
      parentRoute: typeof IntranetAuthedRouteRoute
    }
    '/intranet/_authed/relatorios': {
      id: '/intranet/_authed/relatorios'
      path: '/relatorios'
      fullPath: '/intranet/relatorios'
      preLoaderRoute: typeof IntranetAuthedRelatoriosRouteImport
      parentRoute: typeof IntranetAuthedRouteRoute
    }
    '/intranet/_authed/projetos': {
      id: '/intranet/_authed/projetos'
      path: '/projetos'
      fullPath: '/intranet/projetos'
      preLoaderRoute: typeof IntranetAuthedProjetosRouteImport
      parentRoute: typeof IntranetAuthedRouteRoute
    }
    '/intranet/_authed/financeiro': {
      id: '/intranet/_authed/financeiro'
      path: '/financeiro'
      fullPath: '/intranet/financeiro'
      preLoaderRoute: typeof IntranetAuthedFinanceiroRouteImport
      parentRoute: typeof IntranetAuthedRouteRoute
    }
    '/intranet/_authed/documentos': {
      id: '/intranet/_authed/documentos'
      path: '/documentos'
      fullPath: '/intranet/documentos'
      preLoaderRoute: typeof IntranetAuthedDocumentosRouteImport
      parentRoute: typeof IntranetAuthedRouteRoute
    }
    '/intranet/_authed/clientes': {
      id: '/intranet/_authed/clientes'
      path: '/clientes'
      fullPath: '/intranet/clientes'
      preLoaderRoute: typeof IntranetAuthedClientesRouteImport
      parentRoute: typeof IntranetAuthedRouteRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface IntranetAuthedRouteRouteChildren {
  IntranetAuthedClientesRoute: typeof IntranetAuthedClientesRoute
  IntranetAuthedDocumentosRoute: typeof IntranetAuthedDocumentosRoute
  IntranetAuthedFinanceiroRoute: typeof IntranetAuthedFinanceiroRoute
  IntranetAuthedProjetosRoute: typeof IntranetAuthedProjetosRoute
  IntranetAuthedRelatoriosRoute: typeof IntranetAuthedRelatoriosRoute
  IntranetAuthedReunioesRoute: typeof IntranetAuthedReunioesRoute
  IntranetAuthedIndexRoute: typeof IntranetAuthedIndexRoute
}

const IntranetAuthedRouteRouteChildren: IntranetAuthedRouteRouteChildren = {
  IntranetAuthedClientesRoute: IntranetAuthedClientesRoute,
  IntranetAuthedDocumentosRoute: IntranetAuthedDocumentosRoute,
  IntranetAuthedFinanceiroRoute: IntranetAuthedFinanceiroRoute,
  IntranetAuthedProjetosRoute: IntranetAuthedProjetosRoute,
  IntranetAuthedRelatoriosRoute: IntranetAuthedRelatoriosRoute,
  IntranetAuthedReunioesRoute: IntranetAuthedReunioesRoute,
  IntranetAuthedIndexRoute: IntranetAuthedIndexRoute,
}

const IntranetAuthedRouteRouteWithChildren =
  IntranetAuthedRouteRoute._addFileChildren(IntranetAuthedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CasesRoute: CasesRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  IntranetAuthedRouteRoute: IntranetAuthedRouteRouteWithChildren,
  IntranetLoginRoute: IntranetLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
